version: '2'

services:
  base-workspace:
    build:
      context: ./centos-base-workspace
    ports:
      - "${WORKSPACE_PORT}:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_VERSION=${CONSUL_VERSION}
      - CONSULUI_VERSION=${CONSULUI_VERSION}
      - CONSULTEMPLATE_VERSION=${CONSULTEMPLATE_VERSION}
      - RUBY_VERSION=${RUBY_VERSION}
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}              # minimal server options

  application:
    build:
      context: ./centos-application
    depends_on:
      - base-workspace
    ports:
      - "${APPLICATION_PORT}:22"
    volumes_from:
      - base-workspace
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPLICATION}:/application
    environment:
      #- CONSUL_AGENT=application                     # consul agent hostname/IP
      #- CONSUL_PORT=8500                             # consul agent port
      #- CONSUL_KEYPREFIX=path/prefix/                # consul key prefix path
      - CONSUL_SERVICENAME=openssh                    # consul service name
      - CONSUL_SERVICETAGS=dev                        # consul service tag
      - CONSUL_SERVICEPORT=2222                       # consul service port
      - CONSUL_CHECKTYPE=tcp                          # consul health check type
      #- OPENSSH_PASSWORDAUTHENTICATION=no            # enable authentication by password
      #- OPENSSH_SFTPUSERS=                           # SFTP users to create (comma separated list)
      #- OPENSSH_SFTPGROUP=sftp                       # SFTP group for users
      #- OPENSSH_SFTPGID=101                          # GID of SFTP group
      #- OPENSSH_SFTPCHROOT=1                         # enable chroot for SFTP
      #- OPENSSH_SFTPCHROOTUSERDIR=public_html        # user directory inside chroot
    tty: true
    networks:
      - frontend
      - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  base_workspace:
    driver: "local"
