version: '3.2'

services:

#-------------------------------------------------------------------
# ALL FEATURES
#-------------------------------------------------------------------
  consul:
    image: zeroc0d3lab/centos-consul
    ports:
      - "8500:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}                   # minimal server options

  application:
    depends_on:
      - consul
    build:
      context: .
    ports:
      - "${APPLICATION_PORT}:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_APPLICATION}:/home/docker/workspace
    environment:
      - SSH_AUTHORIZED_KEYS=${SSH_AUTHORIZED_KEYS}
      - SSH_USER=${SSH_USER}
      - SSH_USER_PASSWORD=${SSH_USER_PASSWORD}
      - SSH_USER_PASSWORD_HASHED=${SSH_USER_PASSWORD_HASHED}
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
      - CONSUL_SERVICENAME=${CONSUL_SERVICENAME}                             # consul service name
      - CONSUL_SERVICETAGS=${CONSUL_SERVICETAGS}                             # consul service tag
      - CONSUL_SERVICEPORT=${CONSUL_SERVICEPORT}                             # consul service port
      - CONSUL_CHECKTYPE=${CONSUL_CHECKTYPE}                                 # consul health check type
    tty: true
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  application:
    driver: "local"