version: '2'

services:
  application:
    build:
      context: ./centos-application-lite
    # image: zeroc0d3lab/centos-application-lite
    ports:
      - "${APPLICATION_PORT}:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPLICATION}:/application
    environment:
      - CONSUL_VERSION=${CONSUL_VERSION}
      - CONSULUI_VERSION=${CONSULUI_VERSION}
      - CONSULTEMPLATE_VERSION=${CONSULTEMPLATE_VERSION}
      - RUBY_VERSION=${RUBY_VERSION}
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}              # minimal server options
      #- CONSUL_AGENT=application                     # consul agent hostname/IP
      #- CONSUL_PORT=8500                             # consul agent port
      #- CONSUL_KEYPREFIX=path/prefix/                # consul key prefix path
      - CONSUL_SERVICENAME=openssh                    # consul service name
      - CONSUL_SERVICETAGS=dev                        # consul service tag
      - CONSUL_SERVICEPORT=2222                       # consul service port
      - CONSUL_CHECKTYPE=tcp                          # consul health check type
      #- OPENSSH_PASSWORDAUTHENTICATION=no            # enable authentication by password
      #- OPENSSH_SFTPUSERS=                           # SFTP users to create (comma separated list)
      #- OPENSSH_SFTPGROUP=sftp                       # SFTP group for users
      #- OPENSSH_SFTPGID=101                          # GID of SFTP group
      #- OPENSSH_SFTPCHROOT=1                         # enable chroot for SFTP
      #- OPENSSH_SFTPCHROOTUSERDIR=public_html        # user directory inside chroot
    networks:
      - frontend
      - backend

  postgres:
    build: ./postgres
    links:
      - application
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend


### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  application:
    driver: "local"
  postgres:
    driver: "local"
